name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # GITHUB_TOKEN
          committer_token: ${{secrets.GITHUB_TOKEN}}
          user: sargentsteveEr
          plugin_introduction: yes
          plugin_lines: yes
          # add c#, java, when it gets to be too much
          plugin_languages_ignored: HLSL, ShaderLab
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
